import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Darker_Grotesque } from "next/font/google";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    {/* <style>
        font-family: ${font.style.fontFamily}, sans-serif;
    </style> */}

      <body>
        {children}
      </body>
    </html>
  );
}
